### ISSUE TITLE
middle mouse button can't be used to paste a text

### ISSUE THREAD

**Issue by bachradsusi** [LINKIWI/modern-paste#30]
For me it's quite common to select a text using left mouse button and paste it using middle mouse button. But it doesn't work with this tool. It's probably due to javascript used in the input field instead of standard html textarea.

**Comment by LINKIWI** [comment]
Is this standard behavior on web? I have never heard of the middle mouse button being mapped to ctrl+v.

I'm happy to accept a PR for this functionality, but I have no way of testing it, since none of my input devices have a middle mouse button.

**Comment by bachradsusi** [comment]
It's standard behavior on Linux desktop.

I guess that Fedora infrastructure can help as it's deployed on  paste.fedoraproject.org

**Comment by dkopecek** [comment]
@LINKIWI I would say many (Linux) users expect it to work. And of course many don't know about it or they don't have a middle button on their mouse/pointing/pasting device so they don't care :-)

For example, middle button pasting was missing, requested and finally implemented some time ago in the Atom project: https://github.com/atom/atom/issues/2244. There are probably many more examples of users requesting this feature in their favorite projects ;-)

**Comment by LINKIWI** [comment]
Thanks for the feedback. Without a middle mouse button on any of my devices, the best I can do is accept a patch PR for this feature.

However, it seems like this may be a bug in the upstream CodeMirror project. MP uses CodeMirror for all paste input boxes.

[Paste by using middle click in firefox not working](https://github.com/codemirror/CodeMirror/issues/931)
[CodeMirror doesn't paste with middle mouse click in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=953389)

Is this bug reproducible in Chrome (or any non-FF)?

**Comment by vmojzis** [comment]
It is not. At least in Chromium middle mouse click works as expected (paste selected text).

**Comment by keszybz** [comment]
Same result here (Fedora 25, gnome wayland). middle-click in FF51 does nothing, but pastes text on google chrome 56.

**Comment by pypingou** [comment]
The behavior can be emulated on a linux desktop if you click on both left and right button at the same time (or if you use a touchpad when you do a three fingers tap)

**Comment by nirik** [comment]
Oddly, the upstream mozilla bug is now closed (They show a commit in 2016 having fixed it), but it still happens to me with firefox-51.0.1.

**Comment by nirik** [comment]
Any ideas here? firefox seems to indicate this is fixed from their end now... is the issue in codemirror now? Or did firefox not really fix it ⁉️

**Comment by gholms** [comment]
FWIW, Atom fixed this in atom/atom#4211 using a listener for mouse button 2.

**Comment by UweMenges** [comment]
Is this also related to select-to-X-selection not working on https://paste.fedoraproject.org/ with Firefox 54.0 (64-bit)? Works in Google Chrome 60.0.3112.78 (Official Build) (64-bit).

**Comment by marticak** [comment]
Fixing this would really be useful.  It seems still broken to me.  I can happily paste using the mouse wheel "here",  but not in my modern-paste instance.
